"""Build three localized landing pages using the site's existing navigation/head."""
from pathlib import Path
import re, html
COPY={
'en':dict(title='Change the words.<br>Keep the slide.',intro='A date changed. A heading needs work. Edit text in an image-based PDF without rebuilding the whole presentation.',badge='IMAGE PDF EDITOR · MADE FOR MAC',download='View on the App Store',watch='Watch the real workflow',trust='Free editing & export · On-device document processing',before='Original image',after='Edited result',compare='Drag to compare the original and edited slide',proof='Same photo. A different message.',proofbody='Text over stone, shadows, and fine detail. Compare the original image with the actual background restoration and replacement text.',note='Generated sample image, actual on-device output. Restoration quality varies with the background; hidden details and original fonts cannot be recovered exactly.',demo='See the edit happen.',demobody='OCR selection, text replacement, restoration preview, and a new PDF — recorded in the actual Mac app.',lang='Demo language',pending='Preview of version 1.2 · Submitted for App Review. The App Store may still show the previous version.',caption='30-second demo · Some steps play at 2×, as labeled in the video · No audio',steps='From a flattened slide to a useful edit.',cards=[('01 / SELECT','Find the text','Open a PDF or image and select an OCR text region.'),('02 / REFINE','Make it fit','Change the words, font, color, or spacing. Inspect and adjust the restored background before applying it.'),('03 / EXPORT','Keep the original','Use undo and redo, then export a new PDF, image, video, or GIF.')],faq='A few things to know.',qa=[('Is editing free?','All editing and export features are free. Version 1.2 adds a voluntary one-time developer tip in Help or Settings. Each purchase is a separate charge. It unlocks nothing and is not a subscription.'),('Does my PDF leave my Mac?','OCR and image processing run locally. Optional purchases use Apple’s payment services; your document is not sent for processing.'),('Will every background look perfect?','No. Photos, patterns, small text, and low-resolution scans can need manual adjustment. Compare the result and refine the restoration area before exporting.'),('Which Macs and languages are supported?','Requires macOS 15.1 or later and an Apple Silicon Mac (M1 or later). The 1.2 interface supports English, Korean, Japanese, Simplified Chinese, and Traditional Chinese.')],end='Your slide. One small correction.',endbody='Keep the presentation moving.',more='Explore all features',skip='Skip to content'),
'ko':dict(title='슬라이드는 그대로.<br>글자만 새롭게.',intro='바뀐 날짜, 다듬고 싶은 제목. 이미지로 된 PDF에서도 발표 자료 전체를 다시 만들지 않고 필요한 문구를 수정하세요.',badge='이미지 PDF 편집기 · MAC 전용',download='App Store에서 보기',watch='실제 편집 과정 보기',trust='편집·내보내기 무료 · 문서 처리는 Mac 안에서',before='원본 이미지',after='실제 수정 결과',compare='슬라이더를 움직여 원본과 수정 결과 비교',proof='같은 사진 위에, 새로운 문장.',proofbody='돌의 질감, 그림자, 작은 디테일이 있는 배경입니다. 원본과 실제 배경 복원·텍스트 교체 결과를 직접 비교해 보세요.',note='가상 행사용 생성 이미지에 실제 온디바이스 처리를 적용한 결과입니다. 배경에 따라 품질이 달라지며 가려진 디테일이나 원래 글꼴을 정확히 복원하지는 못합니다.',demo='편집하는 순간을 보세요.',demobody='OCR 선택부터 문구 수정, 복원 결과 확인, PDF 저장까지. 실제 Mac 앱에서 촬영했습니다.',lang='데모 언어',pending='1.2 버전 미리보기 · App Store 심사 제출 완료. 현재 스토어에는 이전 버전이 표시될 수 있습니다.',caption='30초 데모 · 일부 구간은 영상에 표시된 2배속 · 소리 없음',steps='이미지 슬라이드도, 필요한 부분부터.',cards=[('01 / 선택','글자를 찾고','PDF나 이미지를 열어 OCR로 인식된 글자 영역을 선택합니다.'),('02 / 보정','내 문구에 맞추고','내용·글꼴·색상·자간을 바꾸고, 복원된 배경을 확인하고 조정한 뒤 적용합니다.'),('03 / 저장','원본은 보관하세요','실행 취소와 다시 실행으로 수정하고, 새 PDF·이미지·영상·GIF로 내보냅니다.')],faq='사용 전에 궁금한 점.',qa=[('편집은 무료인가요?','모든 편집·내보내기 기능은 무료입니다. 1.2 버전의 도움말·설정에서 선택적으로 개발을 응원할 수 있습니다. 구매할 때마다 별도 결제되는 일회성 팁이며, 구독이나 추가 기능은 없습니다.'),('PDF가 외부로 전송되나요?','OCR와 이미지 처리는 Mac 안에서 이루어집니다. 선택적 결제에는 Apple 결제 서비스를 이용하며, 문서 처리용으로 파일을 전송하지 않습니다.'),('어떤 배경이든 완벽하게 복원되나요?','아닙니다. 사진·무늬·작은 글자·저해상도 스캔은 수동 보정이 필요할 수 있습니다. 결과를 비교하고 복원 범위를 조정한 뒤 저장하세요.'),('어떤 Mac과 언어를 지원하나요?','macOS 15.1 이상, Apple Silicon Mac(M1 이상)이 필요합니다. 1.2 앱 화면은 영어·한국어·일본어·중국어 간체·번체를 지원합니다.')],end='작은 수정 하나로,<br>발표를 이어가세요.',endbody='원본은 남기고, 필요한 부분을 바꾸세요.',more='전체 기능 보기',skip='본문으로 이동'),
'ja':dict(title='スライドはそのまま。<br>言葉を新しく。',intro='日付の変更も、見出しの修正も。画像になったPDFの文字を、資料全体を作り直さずに編集できます。',badge='画像PDFエディタ · MAC専用',download='App Storeで見る',watch='実際の編集を見る',trust='編集・書き出しは無料 · 書類の処理はMac上で',before='元の画像',after='実際の編集結果',compare='スライダーで元の画像と編集結果を比較',proof='同じ写真に、新しい言葉を。',proofbody='石の質感、影、細かな模様のある背景。元の画像と、実際に背景を復元して文字を置き換えた結果を比較できます。',note='架空のイベント用に生成した画像を、実際にオンデバイスで処理した結果です。背景によって品質は変わります。隠れた細部や元のフォントの正確な復元は保証されません。',demo='編集の流れを、そのまま。',demobody='OCRで選択し、文字を修正。背景の復元を確認してPDFに保存するまで、実際のMacアプリで撮影しました。',lang='デモの言語',pending='バージョン1.2のプレビュー · App Store審査に提出済み。ストアには旧バージョンが表示される場合があります。',caption='30秒のデモ · 一部は映像内に表示した2倍速 · 音声なし',steps='画像のスライドも、必要な部分から。',cards=[('01 / 選択','文字を見つける','PDFや画像を開き、OCRで認識された文字の領域を選択します。'),('02 / 調整','言葉を整える','文字、フォント、色、字間を変更。復元した背景を確認・調整してから適用します。'),('03 / 保存','原本を残す','取り消しとやり直しを使い、新しいPDF、画像、動画、GIFとして書き出します。')],faq='使う前に知っておきたいこと。',qa=[('編集は無料ですか？','すべての編集・書き出し機能は無料です。1.2ではヘルプや設定から任意のチップで開発を応援できます。購入のたびに課金される一回限りのチップで、追加機能やサブスクリプションはありません。'),('PDFは外部に送信されますか？','OCRと画像処理はMac上で行います。任意の購入にはAppleの決済サービスを使いますが、書類を処理のために送信することはありません。'),('どんな背景も完全に復元できますか？','いいえ。写真、模様、小さな文字、低解像度のスキャンでは手動調整が必要な場合があります。結果を比較し、復元範囲を調整してから保存してください。'),('対応するMacと言語は？','macOS 15.1以降とApple Silicon Mac（M1以降）が必要です。1.2の画面は英語、韓国語、日本語、中国語の簡体字・繁体字に対応します。')],end='小さな修正で、<br>次のプレゼンへ。',endbody='原本を残して、必要な言葉を変えましょう。',more='すべての機能を見る',skip='本文へ移動')}
for loc,c in COPY.items():
 p=Path('docs')/('' if loc=='en' else loc)/'index.html';old=p.read_text();prefix='' if loc=='en' else '../';asset=prefix+'media/1.2/'
 head=old.split('</head>', 1)[0]+'</head>';head=re.sub(r'<title>.*?</title>',f'<title>SlideTouch — {re.sub("<.*?>", " ", c["title"])}</title>',head);head=re.sub(r'(<meta (?:name="description"|property="og:description") content=")[^"]*',lambda m:m[1]+html.escape(c['intro'],quote=True),head)
 if 'site.css' not in head: head=head.replace('</head>',f'<link rel="stylesheet" href="{prefix}site.css">\n</head>')
 nav=re.search(r'<nav class="navbar">.*?</nav>',old,re.S)[0];footer=re.search(r'<footer>.*?</footer>',old,re.S)[0]
 nav=re.sub(r'href="/(ko/|ja/)?" class="lang-option"',lambda m:'href="/SlideTouch-support/'+(m[1] or '')+'" class="lang-option"',nav)
 cards=''.join(f'<article><span>{a}</span><h3>{b}</h3><p>{d}</p></article>' for a,b,d in c['cards']);faq=''.join(f'<details><summary>{q}</summary><p>{a}</p></details>' for q,a in c['qa'])
 options=''.join(f'<option value="{l}"'+(' selected' if l==loc else '')+f'>{label}</option>' for l,label in [('en','English'),('ko','한국어'),('ja','日本語'),('zh-Hans','简体中文'),('zh-Hant','繁體中文')])
 p.write_text(head+f'''<body class="site-theme landing"><a class="skip" href="#main">{c['skip']}</a>{nav}
<main id="main"><header class="landing-hero container"><div class="hero-copy"><p class="eyebrow">{c['badge']}</p><h1>{c['title']}</h1><p class="lead">{c['intro']}</p><div class="actions"><a class="primary" href="https://apps.apple.com/app/id6758996914">{c['download']} ↗</a><a href="#demo">{c['watch']} ↓</a></div><p class="trust">{c['trust']}</p></div><figure class="hero-photo"><img src="{asset}{loc}-edited.jpg" width="1440" height="810" alt="{c['after']}" fetchpriority="high"><figcaption>{c['after']} · SlideTouch 1.2</figcaption></figure></header>
<section class="proof-section" id="text-edit-example"><div class="container"><p class="eyebrow">BEFORE / AFTER</p><h2>{c['proof']}</h2><p class="section-intro">{c['proofbody']}</p><div class="compare" style="--split:50%"><img src="{asset}{loc}-edited.jpg" width="1440" height="810" alt="{c['after']}" loading="lazy"><img class="before-image" src="{asset}{loc}-input.jpg" width="1440" height="810" alt="{c['before']}" loading="lazy"><span class="compare-label before-label">{c['before']}</span><span class="compare-label after-label">{c['after']}</span><span class="compare-line" aria-hidden="true"></span></div><label class="range-label" for="compare-range">{c['compare']}</label><input id="compare-range" type="range" min="0" max="100" value="50" aria-label="{c['compare']}"><p class="fineprint">{c['note']}</p></div></section>
<section class="container demo-section" id="demo"><div class="demo-heading"><div><p class="eyebrow">IN THE APP</p><h2>{c['demo']}</h2><p class="section-intro">{c['demobody']}</p></div><label>{c['lang']}<select id="demo-language">{options}</select></label></div><video id="demo-video" controls playsinline preload="none" poster="{asset}{loc}-poster.jpg" aria-label="{c['demo']}"><source src="{asset}{loc}-demo.mp4" type="video/mp4"></video><p class="fineprint">{c['caption']}</p><p class="release-note">{c['pending']}</p></section>
<section class="container workflow"><h2>{c['steps']}</h2><div class="steps">{cards}</div><a href="features.html">{c['more']} →</a></section><section class="container faq"><h2>{c['faq']}</h2>{faq}</section><section class="closing"><div class="container"><h2>{c['end']}</h2><p>{c['endbody']}</p><a class="primary" href="https://apps.apple.com/app/id6758996914">{c['download']} ↗</a></div></section></main>{footer}<script src="{prefix}lang-switcher.js"></script><script src="{prefix}landing.js"></script></body></html>''')
